name: Build Docs(Pandoc)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gzip tar perl pandoc fonts-firacode fonts-noto-core fonts-noto-extra fonts-noto-color-emoji fonts-noto-mono fonts-noto-cjk fonts-noto-cjk-extra
      - name: Install texlive
        run: |
          cd /tmp
          curl -L -o install-tl-unx.tar.gz https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          zcat < install-tl-unx.tar.gz | tar xf -
          cd install-tl-2*
          sudo perl ./install-tl --no-interaction --scheme=small
          install_dir=$(ls -d /usr/local/texlive/install-tl-* 2>/dev/null | sort -V | tail -n 1)
          year=$(basename "$install_dir" | grep -oP 'install-tl-\K\d+')
          platform=$(uname -m)-$(uname -s | tr '[:upper:]' '[:lower:]') 
          case $platform in
            "x86_64-linux")
              platform="x86_64-linux"
            ;;
            "i686-linux")
              platform="i386-linux"
            ;;
            "x86_64-darwin")
              platform="universal-darwin"
            ;;
            "arm64-darwin")
              platform="arm64-darwin"
            ;;
            *)
              exit 1
            ;;
          esac
          export PATH="/usr/local/texlive/$year/bin/$platform:$PATH"
      - name: Install tex packages
        run: |
          tlmgr init-usertree
          tlmgr update --all || echo ''
          tlmgr install xetex xelatex amsfonts amsmath lm unicode-math iftex listings fancyvrb longtable booktabs multirow graphicx bookmark xcolor soul  geometry setspace babel xecjk framed fontspec bidi mathspec upquote microtype csquotes natbib biblatex bibtex biber upquote parskip xurl footnotehyper footnote

      - name: Build Documentation
        run: |
          pandoc --defaults ./scripts/pandoc-opts.yml

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: pdf/*
