name: Build Docs(Pandoc)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended fonts-firacode fonts-noto-core fonts-noto-extra fonts-noto-color-emoji fonts-noto-mono fonts-noto-cjk fonts-noto-cjk-extra

      - name: Build Documentation
        run: |
          chmod +x scripts/render-pandoc.sh
          ./scripts/render-pandoc.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output.pdf
          path: pdf/*
